name: Go Building

on:
  push:
    branches:
      - master
      - develop
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Go 1.18.3
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.3'
        run: go env

      - name: Building kepler
        run: CGO_ENABLED=0 go build -o kepler-cli github.com/extvos/kepler

      - name: Building demo
        run: CGO_ENABLED=0 go build -o kepler-demo github.com/extvos/demo

      - name: Testing kepler
        run: go test -v github.com/extvos/kepler

      - name: Testing demo
        run: go test -v github.com/extvos/demo