name: Go Building

on:
  push:
    branches:
      - master
      - develop
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Go 1.18.3
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'

      - name: Preparing Building
        run: |
          pwd
          ls -l
          mkdir build/

      - name: Building 
        run: |
          CGO_ENABLED=0 go build -o build/kepler-cli github.com/extvos/kepler
          CGO_ENABLED=0 go build -o build/kepler-demo github.com/extvos/kepler-demo

      - name: Testing
        run: |
          go test -v github.com/extvos/kepler
          go test -v github.com/extvos/kepler-demo